---
- name: "Preflight - Fail if target host is not stable for this Role."
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in ntp_stable_os)

- name: "Include OS family specific variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install NTP on Redhat Derivatives."
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ntp_prerequisites }}"
  when: ansible_os_family == "RedHat"

- name: "Install NTP on Debian Derivatives."
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ntp_prerequisites }}"
  when: ansible_os_family == 'Debian'

- name: "Configure NTP."
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
    backup: 'yes'
  notify:
    - restart ntp
